[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"

[[bin]]
name = "day-01-1"
path = "src/day-01-1.rs"

[[bin]]
name = "day-01-2"
path = "src/day-01-2.rs"

[[bin]]
name = "day-02-1"
path = "src/day-02-1.rs"

[[bin]]
name = "day-02-2"
path = "src/day-02-2.rs"

[[bin]]
name = "day-03-1"
path = "src/day-03-1.rs"

[[bin]]
name = "day-03-2"
path = "src/day-03-2.rs"

[[bin]]
name = "day-04-1"
path = "src/day-04-1.rs"

[[bin]]
name = "day-04-2"
path = "src/day-04-2.rs"
